# netlify.toml

# Build settings for your frontend app
[build]
  base    = "frontend"
  publish = "build"         # ✅ only "build", not "frontend/build"
  command = "npm run build"

# Function settings for your backend
[functions]
  directory = "netlify/functions"
